"""Update Migrations

Revision ID: b5ce63264625
Revises: 258e98710775
Create Date: 2020-09-20 01:27:34.932752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ce63264625'
down_revision = '258e98710775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###
